### ISSUE TITLE
Storing Canvas contents

### ISSUE THREAD

**Issue by KnorrFG** [Ethosa/nodesnim#15]
Hey, 
Im looking for a library where I can do simple graph visualization and use Gui elements easily. Yours seems like a good fit. However, for me it is important to be able to save the canvas contents to an image file, and reading through your examples and the documentation, that doesn't seem to be possible, right?. 
Oh, and it would be important to able to render text in the canvas.

**Comment by Ethosa** [comment]
Fix in https://github.com/Ethosa/nodesnim/commit/c2bd99cabb904a03105ae526fc9f128ac389f8b8
