### ISSUE TITLE
Please push `Re-run` jobs button if GitHub Actions failed.

### ISSUE THREAD

**Issue by jiro4989** [Ethosa/nodesnim#7]
https://github.com/Ethosa/nodesnim/blob/master/.github/workflows/test.yml#L58

You do not have to change code if `apt install` failed.
GitHub Actions can retry test with button.

https://github.com/Ethosa/nodesnim/runs/712242252?check_suite_focus=true

See right area.
I think that you can push `Re-run` jobs button.

`apt install` sometimes fails.
You try push `Re-run` jobs button if it failed.

**Comment by jiro4989** [comment]
hmm... My tests failed too
https://github.com/jiro4989/nodesnim/runs/712886899?check_suite_focus=true

**Comment by jiro4989** [comment]
> 2020-05-27T11:56:49.0450138Z E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_237-3ubuntu10.40_amd64.deb  404  Not Found [IP: 52.177.174.250 80]

**Comment by jiro4989** [comment]
http://azure.archive.ubuntu.com/ubuntu/ubuntu/pool/

directory is not found... ?

**Comment by jiro4989** [comment]
hmm
https://twitter.com/dave_universetf/status/1247252192899117063

**Comment by jiro4989** [comment]
I think that `azure.archive.ubuntu.com` might have a incident.
Please wait a few hours.

**Comment by Ethosa** [comment]
Yes, thanks, I already noticed and decided to wait, this error was in the morning...

**Comment by Ethosa** [comment]
Oh, it seems everything is back to normal. :)
![image](https://user-images.githubusercontent.com/49402667/83036303-9ed2a480-a064-11ea-9171-0244014aae81.png)

**Comment by jiro4989** [comment]
yay 😍
